### ISSUE TITLE
[Featuresuggestion] Keyboardcontrols

### ISSUE THREAD

**Issue by The1andONLYdave** [TobiasBielefeld/Simple-Brick-Games#2] opened 2017-06-06 18:32 UTC
Hi,
what do you think about adding keyboardcontrols (wasd for move, L fire, P pause for example? Or choose your own in preferences?). 

As there are more n more android devices with physical keyboard like the official Samsung Galaxy Keyboard-addon for S7 and S8 iirc, BlackBerry Priv and KeyOne, Chromebooks capable of running Android Apps...

Greetings,
Dave

**Comment by TobiasBielefeld** [comment] 2017-06-06 20:44
Good idea, I'll add it :)

**Comment by TobiasBielefeld** [comment] 2017-06-15 19:12
Soo it works now, but there is a problem: Somehow you can only press one key at a time. I am not sure if this issue is caused by my Android emulator, but I will try to improve that.

I released the new version. Keyboard Input and the key assignment can now be changed in the settings :)

**Comment by The1andONLYdave** [comment] 2017-06-16 15:08
Great, just tested it 👍 

On my BlackBerry Priv (Android 6 from June 2017) it's possible in Game A to shoot while driving.
I can also press left, right and shooting together,  which results in some funny stuttering movement :-D so three keys are possible.
Will test later on a Chromebook running 7.1.1

**Comment by The1andONLYdave** [comment] 2017-06-16 15:15
Ok, on the chromebook it's working with three keys simultaneously, too. Only 'issue' there is that if i hold the shoot-key and start driving in a direction it sometimes lags (very small lag) before the car starts driving, maybe something with the key-polling. But i won't mind it, because the chromebook is running a pre-beta of ChromeOS with a beta/pre-beta Android Runtime not fully optimized for endusers yet. Maybe on a 3d-fps-game my mileage might differ, but this game is still very playable ;)

Thank you!

**Comment by TobiasBielefeld** [comment] 2017-06-16 21:46
Oh nice to hear :D Then my issue is just caused by the Android PC Emulator. I should try Chrome/Chromium OS with my app, too. Maybe i can improve that behavior :)

**Comment by TobiasBielefeld** [comment] 2017-07-28 12:24
I finally got a little Android Tablet with a keyboard, so I could test the app. After some testing I thought, maybe I should limit the number of simultaneously pressed arrow keys to 1, because the software keyboard also allows only one at a time.

**Comment by TobiasBielefeld** [comment] 2017-08-16 13:10
I guess i can close this now

**Closed as completed by TobiasBielefeld** 2017-08-16 13:10 UTC
